model:
  kernel_size: 3
  num_layers: 5

training:
  batch_size: 16
  learning_rate: 0.0001
  epochs: 150
  alpha: 0.7
  early_stopping_patience: 3
  use_gpu: true

paths:
  high_res_dir: "./data/highres"
  low_res_dir: "./data/gen"
  output_dir: "./results"
  csv_subdir: "csv"